### ISSUE TITLE
Contrast for Difficulty Title

### ISSUE THREAD

**Issue by ConflictFan** [daredloco/SincUltimate#16]
**Feature description:**
Make the "Ultimate" title in the difficulty dropdown menu bold and in dark red.

Make it something like this `<b><color=#990000>Ultimate</color></b>`

The result should look like this:
![image](https://github.com/daredloco/SincUltimate/assets/119769869/897c659c-6d37-4be8-bf35-19d64336b475)

**Why do you think we need this feature?**
It will help players distinguish the vanilla difficulties from Ultimate mode.

**Comment by daredloco** [comment]
Good idea, will try to include it in v1.2.1
