### ISSUE TITLE
Mod options window changes

### ISSUE THREAD

**Issue by ConflictFan** [daredloco/SincUltimate#22]
**Feature description:**

There is too much distance between the Debug mode checkbox and the rest of the mod description.
I recommend shrinking the distance, because with the vanilla window size, the checkbox isn't visible without scrolling.

From the top:
![image](https://github.com/daredloco/SincUltimate/assets/119769869/3a3c4a9d-16e0-4182-8317-9efde2f90e0d)
Scrolled down:
![image](https://github.com/daredloco/SincUltimate/assets/119769869/82e8137a-6e20-42c3-8445-2ab41ba15e0d)

Instead of playing around with rectangle whatever sizes, I suggest changing the text part to this, which reduces the font sizes and conveniently gives me more credit by putting me beside you ;D
`var title = WindowManager.SpawnLabel();`
`title.text = "<b>Ultimate Difficulty</b>";`
`title.fontSize = 20;`
`var author = WindowManager.SpawnLabel();`
`author.text = "by daRedLoCo and CF";`
`author.fontSize = 16;`
`var description = WindowManager.SpawnLabel();`
`description.text = "Brings a real challenge to Software Inc!";`
`description.fontSize = 12;`

**Why do you think we need this feature?**
:stonks:

**Comment by daredloco** [comment]
Spawning needs to be made with RECT, but I will see what I can do. Its more or less just a placeholder for now.
But yeah, will be changed in next minor version.
